platform :ios, '10.0'

target 'ExPrivatePod' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'PersonPod', :path => '../'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'ExPrivatePod'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
  end

end
