platform :ios, '10.0'

target 'ExPrivatePod' do
  
  use_frameworks!

  pod 'PrivatePod', :path => '../'
  pod 'NixonUtility', :git => 'https://github.com/powerwolf543/NixonUtility.git'

#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        if target.name == 'PrivatePod'
#            target.build_configurations.each do |config|
#                config.build_settings['SWIFT_VERSION'] = '3.0'
#            end
#        end
#    end
#end

end
